apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: szk54shg5-nodejs
  janus-idp.io/tekton: szk54shg5-nodejs
  backstage.io/kubernetes-id: szk54shg5-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: szk54shg5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
