apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: szk54shg5-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: szk54shg5-nodejs 
  name: szk54shg5-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: szk54shg5-nodejs 
